# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'DocumentReaderSwiftUI-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReaderSwiftUI-sample
  pod 'DocumentReader', '~> 7.5.0'
  pod 'DocumentReaderFullRFID', '~> 7.5.0'
end
