# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DocumentReaderSwiftUI-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReaderSwiftUI-sample
  pod 'DocumentReader', '~> 9.2.0'
  pod 'DocumentReaderFullRFID', '~> 9.2.0'
end
