# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DocumentReaderCertificatePinning' do
  pod 'DocumentReader', '~> 7.4.0'
  pod 'DocumentReaderMRZ', '~> 7.4.0'
end
