# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DocumentReaderCertificatePinning' do
  pod 'DocumentReader', '~> 9.5.0'
  pod 'DocumentReaderMRZ', '~> 9.5.0'
end
