# frozen_string_literal: true


platform :ios, '13.0'
use_frameworks!

target 'DocumentReaderSwiftBleLicense' do
  pod 'DocumentReader', '~> 9.2.0'
  pod 'DocumentReaderFullAuthRFID', '~> 9.2.0'
  pod 'BTDevice', '~> 9.1.0'
end
