# frozen_string_literal: true


platform :ios, '11.0'
use_frameworks!

target 'DocumentReaderSwiftBleLicense' do
  pod 'DocumentReader', '~> 7.2.0'
  pod 'DocumentReaderFullAuthRFID', '~> 7.2.0'
  pod 'BTDevice', '~> 6.8'
end
