# frozen_string_literal: true

platform :ios, '15.0'
use_frameworks!

target 'OnlineProcessing-With-License-Swift' do
  pod 'DocumentReader', '~> 9.1.0'
  pod 'DocumentReaderFullRFID', '~> 9.1.0'
end
