platform :ios, '8.0'

target 'DocumentReaderBoundsSwift-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DocumentReader'
  pod 'DocumentReaderBounds'
end

target 'DocumentReaderCoreSwift-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DocumentReader'
  pod 'DocumentReaderCore'
end
