platform :ios, '9.0'

target 'DocumentReaderFullSwift-sample' do
  use_frameworks!
  pod 'DocumentReaderBeta', '5.2.1402'
  pod 'DocumentReaderFullAuthRFIDBeta', '5.2.3295'
  pod 'BTDeviceBeta', '5.0.52'
end
