# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DocumentReaderRFIDSwiftUISample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReaderSwiftUISample
  pod 'DocumentReader', '~> 7.6.0'
  pod 'DocumentReaderFullRFID', '~> 7.6.0'
end