# frozen_string_literal: true

platform :ios, '15.0'
use_frameworks!

target 'OnlineProcessing-Without-License-Swift' do
  pod 'DocumentReader', '~> 8.1.0'
  pod 'DocumentReaderFullRFID', '~> 8.1.0'
end
