# frozen_string_literal: true


platform :ios, '11.0'
use_frameworks!

target 'DocumentReaderSwiftBleLicense' do
  pod 'DocumentReader', '~> 6.6'
  pod 'DocumentReaderFullAuthRFID', '~> 6.6'
  pod 'BTDevice'
end
