# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DocumentReader-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReader-Swift
  pod 'DocumentReader', '5.5.1899'
  pod 'DocumentReaderFullRFID', '5.5.4239'
end
