# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DocumentReader-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReader-Swift
  pod 'DocumentReader', '5.8.2215'
  pod 'DocumentReaderFullRFID', '5.8.5164'
end
