# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DocumentReader-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DocumentReader-Swift
  pod 'DocumentReader', '6.1.2358'
  pod 'DocumentReaderFullRFID', '6.1.5791'
end
